### PR TITLE
A minor correction on simplescheduler.go

### PR DESCRIPTION
**Pull request by jiwq**

### CODE REVIEW

**Comment by yangwwei** [comment]
hi @jiwq 
Thanks for the PR. Could you pls follow instructions in https://github.com/cloudera/yunikorn-core/blob/master/docs/how-to-contribute.md to send us ICLA? Otherwise, we cannot accept your contribution.

Thanks!

**Comment by jiwq** [comment]
@yangwwei Thanks for your help. I had signed the ICLA and submitted to cla@cloudera.com

**Comment by yangwwei** [comment]
Thank you. Our legal will notify us once they received the ICLA.
BTW, the change is fine, we can merge once we got the notification.

**Comment by yangwwei** [comment]
LGTM, merging this now.

**Pull request merged**
